project:
  type: book
  output-dir: _book
  
book:
  title: "The Eco-Social nexus of Amazon Deforestation"
  author: "Fernando Cymbaluk"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
  
  docx: default

editor: visual

